// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Entity.Models;

public partial class nEdit_DEVContext : DbContext
{
    public nEdit_DEVContext(DbContextOptions<nEdit_DEVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tbl_login> tbl_logins { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbl_login>(entity =>
        {
            entity.HasKey(e => e.login_id).HasName("PK__tbl_logi__C2C971DB76A9AA19");

            entity.Property(e => e.retry_count).HasDefaultValueSql("((0))");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}