// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entity.Models;

[Table("tbl_login")]
public partial class tbl_login
{
    [Key]
    public int login_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string login_name { get; set; }

    [Required]
    [Unicode(false)]
    public string login_pass { get; set; }

    public byte? login_status { get; set; }

    public int? retry_count { get; set; }
}